### ISSUE TITLE
Storing results to an arbitrary MutableMapping

### ISSUE THREAD

**Issue by jakirkham** [radix-ai/graphchain#38]
It would be nice to support the `MutableMapping` interface for storage as well. This would allow users to design a wrapper around their desired storage format as long as it supplies the `MutableMapping` interface.

**Comment by lsorber** [comment]
Hi @jakirkham, that's a good idea, thanks. We had a look and we'll need to add a little functionality on top of `MutableMapping` to make it work (e.g., additional information about the caching mechanism such as its latency and throughput), but essentially it will come down to implementing something like `MutableMapping`.

**Comment by quakberto** [comment]
Hey, thanks for the great tool!

I also think it would be very useful to be able to provide custom storage formats. This would not only make the caching more efficient but also ease the checking of intermediate results (even for non-expert end users).

**Comment by multimeric** [comment]
Am I right in thinking that this is the feature I would need if I wanted to cache my dask `DataFrame` to parquet?

**Comment by lsorber** [comment]
Hi @multimeric, I think we can keep it even more simple if we split the cache into two components:

1. A cache filesystem: here I would like to stick with the current PyFilesystem abstraction.
2. A serialisation & deserialisation method that reads/writes from/to the cache filesystem: currently we use `joblib.dump` and `joblib.load`, but we could add an option to add a custom (de)serialiser.

The API for a (de)serialiser could be
```python
serializer = Callable[[Any, IO], None]
deserializer = Callable[[IO], Any]
```
so that we could write something like
```python
cached_dsk = graphchain.optimize(dsk, serializer=joblib.dump, deserializer=joblib.load)
```
where you could replace `joblib.dump` and `joblib.load` with any custom (de)serialiser you would like to use.

**Comment by multimeric** [comment]
Sounds great! More advanced (but nonessential) functionality could easily be built using that API, such as registering serializers/deserializers.

**Comment by lsorber** [comment]
@multimeric I implemented the proposal above in https://github.com/radix-ai/graphchain/pull/76. Could you have a look to see if that's what you had in mind? If so, I'm happy to merge and release a new version.
