### ISSUE TITLE
Applying this to `Future`s

### ISSUE THREAD

**Issue by multimeric** [radix-ai/graphchain#78]
I have a new issue. The readme/tests only describe how to use `graphchain` with the delayed API or the dask collections, but I'm wondering how I can do so if I'm using [Futures](https://docs.dask.org/en/stable/futures.html), e.g. using `client.submit(func)`. Are these `Futures` just `delayed` behind the scenes, so I can use the delayed optimizer hook? If not, is there any way to apply `graphchain` to them?

**Comment by lsorber** [comment]
Hi @multimeric, I'm unfamiliar with dask's Futures feature, but from a quick glance it seems like it doesn't use dask graphs behind the scenes, but is rather a different kind of backend for concurrent.futures. IIUC, graphchain wouldn't be of much value in that case since tasks are executed as they are submitted.

**Comment by multimeric** [comment]
Indeed. Sorry I forgot to close this issue. The dask folk explained this to me, and it's basically what you said. But for future reference here is the discussion: https://github.com/dask/dask/issues/9228.
